packages:
  - packages/*
  - apps/*

onlyBuiltDependencies:
  - esbuild
minimumReleaseAgeExclude:
  - "@typescript-eslint/parser@8.70.1"
  - "@typescript-eslint/project-service@8.70.1"
  - "@typescript-eslint/scope-manager@8.70.1"
  - "@typescript-eslint/tsconfig-utils@8.70.1"
  - "@typescript-eslint/types@8.70.1"
  - "@typescript-eslint/typescript-estree@8.70.1"
  - "@typescript-eslint/visitor-keys@8.70.1"
allowBuilds:
  "@nestjs/core": true
  argon2: true
  esbuild: true
