DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'pacaembu_app') THEN
    CREATE ROLE pacaembu_app LOGIN PASSWORD 'pacaembu_app' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
  END IF;
END
$$;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
